name: End-to-End Tests
on: [push]

jobs:
  test:
    name: Run TestCafe Tests
    runs-on: windows-latest
    steps:
      - name: Check out the repository
        uses: Hemant-Project/Test_Cafe_Studio
      - name: Run tests
        uses: Hemant-Project/Test_Cafe_Studio@latest
        with:
            args: "chrome tests"